services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      API_USERS_SERVICE_URL: https://jsonplaceholder.typicode.com
      TICKETMASTER_DATABASE_URL: jdbc:postgresql://db:5432/ticketmaster_database
      TICKETMASTER_DATABASE_USERNAME: ticket
      TICKETMASTER_DATABASE_PASSWORD: master
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ticketmaster_database
      POSTGRES_USER: ticket
      POSTGRES_PASSWORD: master
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
