services:
  app:
    container_name: ticket_app
    build: .
    ports:
      - "8080:8080"
    environment:
      API_USERS_SERVICE_URL: https://jsonplaceholder.typicode.com
      TICKETMASTER_DATABASE_URL: jdbc:postgresql://db:5432/ticketmaster_database
      TICKETMASTER_DATABASE_USERNAME: ticket
      TICKETMASTER_DATABASE_PASSWORD: master
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default

  db:
    image: postgres:15
    container_name: ticket_db
    environment:
      POSTGRES_USER: ticket
      POSTGRES_PASSWORD: master
      POSTGRES_DB: ticketmaster_database
    ports:
      - "5432:5432"
    volumes:
      - ./create-db.sh:/docker-entrypoint-initdb.d/create-db.sh
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h db -p 5432 -U ticket" ]
      interval: 10s
      retries: 5
    networks:
      - default
    entrypoint: [ "/bin/bash", "/docker-entrypoint-initdb.d/create-db.sh" ]

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /openapi/openapi.yaml
    volumes:
      - ./openapi_ticketmaster_doc.yml:/openapi/openapi.yaml

  frontend:
    build:
      context: ./ticketmaster-frontend
    ports:
      - "3000:3000"
    depends_on:
      - app

networks:
  default:
    driver: bridge