server:
  servlet:
    context-path: /ticketmaster

spring:
  application:
    name: ticketmaster
  datasource:
    url: ${TICKETMASTER_DATABASE_URL}
    username: ${TICKETMASTER_DATABASE_USERNAME}
    password: ${TICKETMASTER_DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update

api:
  users:
    url: ${API_USERS_SERVICE_URL}
