name: Feature Branch Workflow

on:
  push:
    branches:
      - 'hotfix/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Run Unit Tests
        run: mvn test

      - name: Run Integration Tests
        run: mvn verify

  open-develop-pull-request:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Open Pull Request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Merge Hotfix Branch: ${{ github.ref }}"
          pr_body: "PR gerado automaticamente para mesclar o branch de hotfix no desenvolvimento."
          destination_branch: "develop"
          source_branch: "${{ github.head_ref }}"

  open-master-pull-request:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Open Pull Request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Merge Hotfix Branch: ${{ github.ref }}"
          pr_body: "PR gerado automaticamente para mesclar o branch de hotfix no master."
          destination_branch: "master"
          source_branch: "${{ github.head_ref }}"
